"""OpenClash persistent-source adapter. Command runner is injectable."""

from __future__ import annotations

import subprocess
from dataclasses import dataclass
from typing import Protocol


class CommandError(RuntimeError):
    pass


class Runner(Protocol):
    def run(
        self, argv: list[str], input_text: str | None = None
    ) -> subprocess.CompletedProcess[str]: ...


class SubprocessRunner:
    def run(
        self, argv: list[str], input_text: str | None = None
    ) -> subprocess.CompletedProcess[str]:
        return subprocess.run(
            argv,
            input=input_text,
            text=True,
            capture_output=True,
            check=False,
        )


@dataclass
class OpenClashSSH:
    host: str
    user: str
    source_path: str
    runtime_path: str
    group: str
    runner: Runner = SubprocessRunner()

    def _ssh(self, remote: str, input_text: str | None = None) -> str:
        argv = ["ssh", "-o", "BatchMode=yes", f"{self.user}@{self.host}", remote]
        proc = self.runner.run(argv, input_text)
        if proc.returncode != 0:
            raise CommandError(proc.stderr or proc.stdout or "ssh failed")
        return proc.stdout

    def read_source(self) -> str:
        return self._ssh(f"cat {self.source_path}")

    def write_source(self, text: str) -> None:
        self._ssh(
            f"cat > {self.source_path}.tmp && mv {self.source_path}.tmp {self.source_path}", text
        )

    def reload(self) -> str:
        # Persistent source is authoritative. Runtime file is generated by OpenClash.
        self._ssh("uci get openclash.config.config_path >/dev/null")
        return "ok"
